name: backend CI/CD v0.2

on:
  push:
    branches:
      - "develop"
      - "master"

jobs:
  push-to-develop:
    if: github.ref_name == 'develop'
    name: Test against local
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
      JWT_SECRET: ${{ secrets.JWT_SECRET_DEV }}
      NODE_ENV: ${{ secrets.NODE_ENV_DEV }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install wait-on
        run: npm install --save-dev wait-on

      - name: Install dependencies
        run: npm ci

      - name: Start backend server in the background
        run: |
          npm start > server.log 2>&1 &
          echo "Server started"
      - name: Wait for server to be ready
        run: |
          npx wait-on http://localhost:3000/hello --timeout 30000

      - name: Install Java 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Download SoapUI
        run: |
          wget https://s3.amazonaws.com/downloads.eviware/soapuios/5.7.0/SoapUI-5.7.0-linux-bin.tar.gz
          tar -xzf SoapUI-5.7.0-linux-bin.tar.gz
          mv SoapUI-5.7.0 soapui

      - name: Run SoapUI tests
        run: |
          ./soapui/bin/testrunner.sh -r -j -f reports/ -P baseUrl=http://localhost:3000 soapui-tests/users-soapui-tests.xml

      - name: Checkout Playwright Tests Repo
        uses: actions/checkout@v4
        with:
          repository: p-k-001/users-playwright-tests
          path: playwright-tests
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies for Playwright tests
        working-directory: playwright-tests
        run: |
          npm cache clean --force
          npm ci
          cat package.json  # Debug: show the actual package.json content

      - name: Install Playwright browsers
        working-directory: playwright-tests
        run: npx playwright install chromium

      - name: Run Playwright tests
        working-directory: playwright-tests
        env:
          BASE_URL: http://localhost:3000
        run: npm run test:ci:local
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-local
          path: playwright-report/
          retention-days: 5

  deploy-preview:
    if: github.ref_name == 'develop'
    needs: push-to-develop
    name: Deploy to Vercel Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel Preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

  push-to-master:
    if: github.ref_name == 'master'
    name: Test against staging
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
      JWT_SECRET: ${{ secrets.JWT_SECRET_DEV }}
      NODE_ENV: ${{ secrets.NODE_ENV_DEV }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Java 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Download SoapUI
        run: |
          wget https://s3.amazonaws.com/downloads.eviware/soapuios/5.7.0/SoapUI-5.7.0-linux-bin.tar.gz
          tar -xzf SoapUI-5.7.0-linux-bin.tar.gz
          mv SoapUI-5.7.0 soapui

      - name: Run SoapUI tests
        run: |
          ./soapui/bin/testrunner.sh -r -j -f reports/ -P baseUrl=https://users-api-dev.projects.icanbreakit.eu soapui-tests/users-soapui-tests.xml

      - name: Checkout Playwright Tests Repo
        uses: actions/checkout@v4
        with:
          repository: p-k-001/users-playwright-tests
          path: playwright-tests
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies for Playwright tests
        working-directory: playwright-tests
        run: |
          npm cache clean --force
          npm ci
          cat package.json  # Debug: show the actual package.json content

      - name: Install Playwright browsers
        working-directory: playwright-tests
        run: npx playwright install chromium

      - name: Run Playwright tests
        working-directory: playwright-tests
        env:
          BASE_URL: https://users-api-dev.projects.icanbreakit.eu
        run: npm run test:ci:local
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-staging
          path: playwright-report/
          retention-days: 5
  deploy-master:
    if: github.ref_name == 'master'
    needs: push-to-master
    name: Deploy to Vercel Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel Production
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
