name: backend CI/CD

on:
  push:
    branches:
      - "feature/**"
      - "develop"
      - "master"

jobs:
  test-backend:
    name: Install app and test it
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Set DATABASE_URL environment variable from GitHub Secrets
      - name: Set environment variables
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Install dependencies
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm ci

      - name: Start backend server in the background
        run: npm start &

      - name: Wait for server to be ready
        run: |
          npx wait-on http://localhost:3000

      - name: Install Java 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Download SoapUI
        run: |
          wget https://s3.amazonaws.com/downloads.eviware/soapuios/5.7.0/SoapUI-5.7.0-linux-bin.tar.gz
          tar -xzf SoapUI-5.7.0-linux-bin.tar.gz
          mv SoapUI-5.7.0 soapui

      - name: Run SoapUI tests
        run: |
          ./soapui/bin/testrunner.sh -r -j -f reports/ soapui-tests/users-soapui-tests.xml

#   playwright-tests:
#     if: startsWith(github.ref, 'refs/heads/feature/')
#     name: Playwright Tests (feature)
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Playwright Tests Repo
#         uses: actions/checkout@v4
#         with:
#           repository: p-k-001/users-playwright-tests
#           path: tests
#           token: ${{ secrets.GITHUB_TOKEN }}

#       - name: Install dependencies for Playwright tests
#         working-directory: tests
#         run: npm ci

#       - name: Run Playwright tests
#         working-directory: tests
#         run: npm run test:ci:local
